version: '3.8'
services:
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80" # Nginx는 80 포트에서 실행
      - "443:443" # Nginx는 443 포트에서 HTTPS 실행
    env_file:
      - nginx.env
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt # Certbot 인증서 저장
      - ./nginx/certbot/www:/var/www/certbot # Certbot 인증 파일 저장
        
  pocketbase:
    build:
      context: .
      dockerfile: ./pb/Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - pb.env
    volumes:
      - ./pb/pb_data:/data
      - ./pb/pb_public:/public

  code-server:
    build:
      context: .
      dockerfile: ./code-server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - code-server.env
    volumes:
      - 
