version: '3.8'
services:
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./scripts/subenv_nginx.sh:/scripts/subenv_nginx.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./scripts/autorenew.sh:/scripts/autorenew.sh
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; /scripts/autorenew.sh'"

  pocketbase:
    build:
      context: .
      dockerfile: ./pb/Dockerfile.pb
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./pb/pb_data:/data
      - ./pb/pb_public:/public

  code-server:
    build:
      context: .
      dockerfile: ./vscode/Dockerfile.vscode
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./react_app:/home/user/react_app
      - ./nginx/certbot/conf:/etc/letsencrypt:ro