# code-server 공식 Docker 이미지를 베이스 이미지로 사용
FROM codercom/code-server:latest

# 작업 디렉토리 설정
WORKDIR /home/user/code-server

RUN npm install

# code-server 실행 시 사용할 기본 명령어 설정
CMD ["code-server", "--auth", "password", \
"--bind-addr", "0.0.0.0:8080", "--cert", \
"/etc/letsencrypt/live/${DOMAIN}/fullchain.pem", \
"--cert-key", "/etc/letsencrypt/live/${DOMAIN}/privkey.pem", \
"--disable-telemetry"]

USER user
