FROM nginx:1.19-alpine

RUN addgroup -S user && adduser -S user -G user

WORKDIR /home/user/

# 기존의 Nginx 설정 파일과 기본 사이트 설정 파일 삭제
RUN rm /etc/nginx/nginx.conf && rm /etc/nginx/conf.d/default.conf \
    && chmod +x /scripts/substitute_env.sh

# 스크립트 실행(.env의 환경변수를 적용시키는 스크립트)
CMD ["/bin/sh", "-c", "/scripts/substitute_env.sh && nginx -g 'daemon off;'"]

EXPOSE 80 443

USER user