FROM nginx:1.19-alpine

# 기존의 Nginx 설정 파일과 기본 사이트 설정 파일 삭제
RUN rm /etc/nginx/nginx.conf && rm /etc/nginx/conf.d/default.conf

# 스크립트 실행 권한 부여 (실행은 컨테이너 시작 시점에 CMD 또는 ENTRYPOINT를 통해)
COPY ./scripts/substitute_env.sh /scripts/substitute_env.sh
RUN chmod +x /scripts/substitute_env.sh

# 스크립트 실행을 위한 ENTRYPOINT 또는 CMD 사용
CMD ["/bin/sh", "-c", "/scripts/substitute_env.sh && nginx -g 'daemon off;'"]

EXPOSE 80 443
